# Generated by Django 2.2.12 on 2021-01-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('contact', models.PositiveIntegerField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('bio', models.TextField()),
                ('pan', models.TextField()),
                ('pp', models.ImageField(upload_to='')),
                ('citizenship', models.ImageField(upload_to='')),
            ],
        ),
    ]
