# Generated by Django 2.2.12 on 2021-02-12 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guide',
            name='contact',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
